# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  db:
    image: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_PASSWORD=red_alien
  app:
    image: app
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - 5280:5280
    depends_on:
      db:
        condition: service_healthy
